# =============================================================================
# EasyShop Config Server Configuration
# =============================================================================
# Spring Cloud Config Server configuration following best practices

server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/
            - file:./config/
            - file:../config/
        git:
          uri: ${CONFIG_GIT_URI}
          search-paths:
            - config
            - config/*
          default-label: main
          force-pull: true
          clone-on-start: true
          basedir: /tmp/config-repo
          timeout: 10
          retry:
            initial-interval: 1000
            max-attempts: 6
            max-interval: 2000
            multiplier: 1.1
  security:
    user:
      name: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}

# Management endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,configprops
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
  security:
    enabled: true

# Logging configuration
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
  level:
    org.springframework.cloud.config: ${LOG_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_CONFIG}
    com.easyshop: ${LOG_LEVEL_COM_EASYSHOP}
    org.springframework.security: ${LOG_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY}

# Config Server specific settings
config:
  server:
    # Enable encryption/decryption endpoints
    encrypt:
      enabled: true
    # Health check configuration
    health:
      repositories:
        default:
          enabled: true

